fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
      - id: clang-format
        args: [-i]
      - id: cppcheck
        args: [-I./include, --suppress=missingOverride, --suppress=unusedFunction, --suppress=unmatchedSuppression]
      - id: include-what-you-use
        args: [-I./include, -std=c++20]
        exclude: ^tests/
