name: Lint

on:
  push:
    branches: [main, develop]

  pull_request:
    branches: [main, develop]
    types: [opened, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: Debug
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Configure
      run: cmake -B ${{runner.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Lint
      uses: cpp-linter/cpp-linter-action@v2
      id: linter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        style: 'file'
        tidy-checks: ''
        thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}

    - name: Fail fast?!
      if: steps.linter.outputs.checks-failed > 0
      run: exit 1
